---
version: '3'

services:
  deltw:
    container_name: deltw
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/deltw:latest
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - deltw
